name: gesture_password_widget
description: A gesture-unlocking widget for Flutter that supports for high customization.
version: 2.0.1
homepage: https://github.com/LuodiJackShen/GesturePasswordWidget

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
